aliases:
  - &common_cache_key
    key: dependency-cache-{{ checksum ".circleci/config.yml" }}-{{ checksum "package.json" }}
    paths:
      - ~/.opam

version: 2
jobs:
  build:
    docker:
      - image: ocaml/opam:debian-9_ocaml-4.02.3
    steps:
      - run:
          name: "Install Node.js"
          command: |
            curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - checkout
      - restore_cache: *common_cache_key
      - run:
          name: "Initialize opam"
          command: |
            sudo apt-get install -y m4
            opam init --auto-setup --dot-profile=~/.bash_profile
            opam remote add ocamlorg https://opam.ocaml.org -p 0 || true
            opam remote remove default || true
      - run:
          name: "Pin dependency versions"
          command: |
            opam pin add -y odoc
      - run:
          name: "Install dependencies"
          command: |
            npm install
            opam update
            opam install -y odoc
      - run:
          name: "Test"
          command: |
            npm run build
            npm run build-docs
      - store_artifacts:
          path: ~/bs-react-native/docs
      - save_cache: *common_cache_key

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
