aliases:
  - &common_cache_key
    key: dependency-cache-{{ checksum ".circleci/config.yml" }}-{{ checksum "package.json" }}
    paths:
      - ~/.opam
      - node_modules

version: 2
jobs:
  build:
    docker:
      - image: ocaml/opam:debian-9_ocaml-4.02.3
    environment:
      - TERM: dumb
    steps:
      - checkout
      - restore_cache: *common_cache_key
      - run:
          name: "Install Node.js"
          command: |
            curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - run:
          name: "Update opam"
          command: |
            opam update
            opam pin add -y odoc https://github.com/ocaml/odoc.git#e1e73ba
      - run:
          name: "Install dependencies"
          command: |
            opam install -y odoc
            npm install
      - run:
          name: "Test"
          command: |
            npm run build
            npm run build-docs
      - store_artifacts:
          path: ~/bs-react-native/docs
      - save_cache: *common_cache_key

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
